### ISSUE TITLE
Pdb2Mdb.PortablePdbNotSupportedException

### ISSUE THREAD

**Issue by jhalbrecht** [jhalbrecht/XamarinFormsMqttSample#1]
I get these errors at build.

This application runs as expected on UWP. On Android the SettingsView.xaml page can be navigated to however it shows up white without the expected simple grid with settings `Label `and `Input`.

I don't specifically know that this is the problem but...  exception on the android app build... makes me wonder.
 
I increaded the build log verbosity to try and include it here. It was huge and hung incident create page... I left it out.

(Can longer code blocks or logs be entered in with a smaller windows with scroll bars? Does Markdown in GigHub support that?)

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning		Exception of type 'Pdb2Mdb.PortablePdbNotSupportedException' was thrown.
   at Pdb2Mdb.Converter.Convert(String filename)
   at Xamarin.Android.Tasks.ConvertDebuggingFiles.Execute()	MqttSample.Android	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	2031	
Warning		Exception of type 'Pdb2Mdb.PortablePdbNotSupportedException' was thrown.
   at Pdb2Mdb.Converter.Convert(String filename)
   at Xamarin.Android.Tasks.ConvertDebuggingFiles.Execute()	MqttSample.Android	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	2031	
Warning		Exception of type 'Pdb2Mdb.PortablePdbNotSupportedException' was thrown.
   at Pdb2Mdb.Converter.Convert(String filename)
   at Xamarin.Android.Tasks.ConvertDebuggingFiles.Execute()	MqttSample.Android	C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Xamarin\Android\Xamarin.Android.Common.targets	2031	
```
Line 2031 	`<ConvertDebuggingFiles Files="@(_ResolvedPdbFiles)">`
```
<Target Name="_ConvertPdbFiles"
		Inputs="@(_ResolvedPdbFiles)"
		Outputs="@(_ResolvedPdbFiles->'%(RootDir)%(Directory)%(Filename).dll.mdb')"
		DependsOnTargets="_CollectPdbFiles">
	<ConvertDebuggingFiles Files="@(_ResolvedPdbFiles)">
		<Output TaskParameter="ConvertedFiles" ItemName="_ConvertedDebuggingFiles" />
	</ConvertDebuggingFiles>
	<WriteLinesToFile
		File="$(IntermediateOutputPath)$(CleanFile)"
		Lines="@(_ConvertedDebuggingFiles)"
		Overwrite="false" />
</Target>

```

[MqttSampleBuildAndroid.Log.txt](https://github.com/jhalbrecht/XamarinFormsMqttSample/files/2826245/MqttSampleBuildAndroid.Log.txt)

[MqttSampleDebugLog.txt](https://github.com/jhalbrecht/XamarinFormsMqttSample/files/2826111/MqttSampleDebugLog.txt)

**Comment by jhalbrecht** [comment]
For grins I installed vs 2019 preview. Same behavior. The SettingsPage.xaml page seems to load except the screen is blank. I looked for the Pdb2Mdb error but didn't see it. Tired 'night 'night

**Comment by jhalbrecht** [comment]
> This application runs as expected on UWP. On Android the SettingsView.xaml page can be navigated to however it shows up white without the expected simple grid with settings Label and Input.
> 
> I don't specifically know that this is the problem but... exception on the android app build... makes me wonder.

Apparently this is not specifically related to the SettingsView page not showing. See Issue #3
